"""Built-in CLI tools — filesystem, shell, web, http, tasks, sandbox backends.

Prefer ``from agloom_cli.tools import LocalSandbox, BackendProtocol, ...`` for
sandbox types and backends; submodule paths remain available for deep imports.
"""

from .filesystem import (
    copy_file,
    create_directory,
    edit_file,
    file_exists,
    get_file_info,
    grep_files,
    list_directory,
    move_file,
    read_file,
    remove_file,
    search_files,
    write_file,
)
from .http import (
    fetch_json,
    http_delete,
    http_get,
    http_head,
    http_post,
    http_put,
    http_request,
)
from .sandbox import (
    BACKEND_TYPES,
    DEFAULT_EXECUTE_TIMEOUT,
    FILE_NOT_FOUND,
    INVALID_PATH,
    IS_DIRECTORY,
    MAX_BINARY_BYTES,
    MAX_OUTPUT_BYTES,
    PERMISSION_DENIED,
    TRUNCATION_MSG,
    BackendFactory,
    BackendProtocol,
    EditResult,
    ExecuteResponse,
    FileData,
    FileDownloadResponse,
    FileFormat,
    FileInfo,
    FileOperationError,
    FileUploadResponse,
    GlobResult,
    GrepMatch,
    GrepResult,
    LocalSandbox,
    LocalShellBackend,
    LsResult,
    ReadResult,
    SandboxBackendProtocol,
    WriteResult,
    execute_accepts_timeout,
    match_edit_variants,
)
from .shell import (
    get_env_var,
    get_system_info,
    list_env_vars,
    run_shell,
    run_shell_interactive,
    set_env_var,
)
from .task_tracker import (
    clear_task_tracker,
    complete_step,
    create_task_plan,
    get_current_task,
    show_remaining_steps,
    update_task_progress,
)
from .web_search import (
    find_docs,
    search_github,
    search_web,
    web_search,
)
from .working_dir import (
    get_working_directory,
    path_absolute,
    path_basename,
    path_exists,
    path_extension,
    path_is_directory,
    path_is_file,
    path_join,
    path_parent,
    path_stem,
    pop_working_directory,
    push_working_directory,
    set_working_directory,
)

__all__ = [
    "BACKEND_TYPES",
    "BackendFactory",
    "BackendProtocol",
    "DEFAULT_EXECUTE_TIMEOUT",
    "FILE_NOT_FOUND",
    "INVALID_PATH",
    "IS_DIRECTORY",
    "MAX_BINARY_BYTES",
    "MAX_OUTPUT_BYTES",
    "PERMISSION_DENIED",
    "TRUNCATION_MSG",
    "clear_task_tracker",
    "complete_step",
    "copy_file",
    "create_directory",
    # Task tracking
    "create_task_plan",
    "edit_file",
    "EditResult",
    "ExecuteResponse",
    "execute_accepts_timeout",
    "fetch_json",
    "file_exists",
    "FileData",
    "FileDownloadResponse",
    "FileFormat",
    "FileInfo",
    "FileOperationError",
    "FileUploadResponse",
    "find_docs",
    "get_current_task",
    "grep_files",
    "get_env_var",
    "get_file_info",
    "get_system_info",
    # Working directory
    "get_working_directory",
    "GlobResult",
    "GrepMatch",
    "GrepResult",
    "http_delete",
    "http_get",
    "http_head",
    "http_post",
    "http_put",
    # HTTP
    "http_request",
    "list_directory",
    "list_env_vars",
    "LocalSandbox",
    "LocalShellBackend",
    "LsResult",
    "match_edit_variants",
    "move_file",
    "path_absolute",
    "path_basename",
    "path_exists",
    "path_extension",
    "path_is_directory",
    "path_is_file",
    "path_join",
    "path_parent",
    "path_stem",
    "pop_working_directory",
    "push_working_directory",
    # Filesystem
    "read_file",
    "ReadResult",
    "remove_file",
    "SandboxBackendProtocol",
    # Shell
    "run_shell",
    "run_shell_interactive",
    "search_files",
    "search_github",
    "search_web",
    "set_env_var",
    "set_working_directory",
    "show_remaining_steps",
    "update_task_progress",
    # Web search
    "web_search",
    "write_file",
    "WriteResult",
]
