"""How the LangChain provider index maps to the Agloom CLI wizard.

The docs page "All LangChain Python integration providers" lists **every** integration kind:
chat models, vector stores, retrievers, document loaders, tools, and more. The interactive
wizard only configures **one chat LLM** for the CLI agent; other integrations are used from
application code (LangChain), not from this menu.

Brand names below appear on that index but are **not** selectable chat backends here —
typically databases, search, storage, or tooling.
"""

from __future__ import annotations

# Curated from the LangChain "all providers" index — infra / data / tooling (not CLI LLM pickers).
NON_CHAT_INDEX_BRANDS: tuple[str, ...] = (
    "Abso",
    "Acreom",
    "ActiveLoop DeepLake",
    "Ads4GPTs",
    "Aerospike",
    "AG-UI Protocol",
    "AgentQL",
    "AgentSystems",
    "AIM Tracking",
    "AI/ML API",
    "AINetwork",
    "Airbyte",
    "Airtable",
    "Alchemy",
    "Aleph Alpha",
    "Alibaba Cloud",
    "Ampersend",
    "AnalyticDB",
    "Anchor Browser",
    "Annoy",
    "Apache",
    "Apache Cassandra",
    "Apache Doris",
    "Apache Kafka",
    "Apify",
    "Apple",
    "ArangoDB",
    "ArcGIS",
    "Argilla",
    "Arize",
    "Arthur Tracking",
    "arXiv",
    "Ascend",
    "Ask News",
    "AssemblyAI",
    "assistant-ui",
    "Atlas",
    "AwaDB",
    "AZLyrics",
    "BAAI",
    "Beam",
    "Bing",
    "Brave Search",
    "Cassandra",
    "Chroma",
    "Clarifai",
    "ClickHouse",
    "Cloudflare",
    "Confluence",
    "Couchbase",
    "CrewAI",
    "DataStax",
    "Databricks",
    "DeepLake",
    "Discord",
    "Docugami",
    "Dropbox",
    "DuckDB",
    "DuckDuckGo",
    "Elastic",
    "ElevenLabs",
    "Exa",
    "Facebook",
    "FastEmbed",
    "Flowise",
    "GitHub",
    "GitLab",
    "Google Drive",
    "Grafana",
    "Haystack",
    "Jina AI",
    "Kafka",
    "KDB.AI",
    "LanceDB",
    "LangSmith",
    "LlamaIndex",
    "Memgraph",
    "Milvus",
    "MongoDB",
    "MyScale",
    "Neo4j",
    "Oracle",
    "Pinecone",
    "PostgreSQL",
    "Qdrant",
    "Redis",
    "Salesforce",
    "SAP",
    "SingleStore",
    "Slack",
    "Supabase",
    "Tavily",
    "TensorFlow",
    "Typesense",
    "Unstructured",
    "Upstash",
    "Vectara",
    "Vespa",
    "Voyage AI",
    "Weaviate",
    "Wolfram Alpha",
    "Yahoo",
    "You.com",
    "Zapier",
)

# Human-readable titles for ``init_chat_model`` slugs (wizard column).
INIT_CHAT_SLUG_TITLES: dict[str, str] = {
    "anthropic": "Anthropic (Claude)",
    "anthropic_bedrock": "Anthropic on Amazon Bedrock",
    "azure_ai": "Azure AI",
    "azure_openai": "Azure OpenAI",
    "baseten": "Baseten",
    "bedrock": "Amazon Bedrock",
    "bedrock_converse": "Amazon Bedrock (Converse)",
    "cohere": "Cohere",
    "deepseek": "DeepSeek",
    "fireworks": "Fireworks AI",
    "google_anthropic_vertex": "Anthropic on Google Vertex AI",
    "google_genai": "Google Gemini (Google AI)",
    "google_vertexai": "Google Vertex AI",
    "groq": "Groq",
    "huggingface": "Hugging Face",
    "ibm": "IBM watsonx",
    "litellm": "LiteLLM (many hosts)",
    "mistralai": "Mistral AI",
    "nvidia": "NVIDIA NIM / AI endpoints",
    "ollama": "Ollama",
    "openai": "OpenAI",
    "openrouter": "OpenRouter",
    "perplexity": "Perplexity",
    "together": "Together AI",
    "upstage": "Upstage",
    "xai": "xAI (Grok)",
}
